AnthemCode/objects/Event_Templates__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Event Templates</relationshipLabel>
        <relationshipName>Event_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reminder_Template_ID__c</fullName>
        <label>Reminder Template ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Event Template</label>
    <nameField>
        <displayFormat>ET-{00000}</displayFormat>
        <label>Event Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AnthemCode/classes/ReminderEmailService.cls
global class ReminderEmailService {
    @InvocableMethod
    public static void getAccountIds(List<String> eventIds) {
        EmailServiceBatch emailService = new EmailServiceBatch();
        emailService.eventId=eventIds[0];
        emailService.emailTemplateId = [Select ID from EmailTemplate
                                        WHERE ID=:[Select Reminder_Template_ID__c from Event_Templates__c 
                                                   WHERE Event__c=:eventIds[0]].Reminder_Template_ID__c].ID;
        
        Database.executeBatch(emailService, 100);
        //return accountIds;
    }
}