AnthemCode/objects/Event_Templates__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Event Templates</relationshipLabel>
        <relationshipName>Event_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Followup_Template_ID__c</fullName>
        <label>Followup Template ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Followup_Template__c</fullName>
        <label>Followup Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invitation_Template_ID__c</fullName>
        <label>Invitation Template ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invitation_Template__c</fullName>
        <label>Invitation Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Template_ID__c</fullName>
        <label>Registration Template ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Template__c</fullName>
        <label>Registration Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reminder_Template_ID__c</fullName>
        <label>Reminder Template ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reminder_Template__c</fullName>
        <label>Reminder Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thank_you_Id__c</fullName>
        <label>Thank you Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thank_you_template_id__c</fullName>
        <label>Thank you template ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Event Template</label>
    <nameField>
        <displayFormat>ET-{00000}</displayFormat>
        <label>Event Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AnthemCode/classes/EventTemplateSetupCtrl.cls
public class EventTemplateSetupCtrl {
    public Boolean show{get;set;}
    public String selectedRegistrationTemplate{get;set;}
    public String selectedInvitationTemplate{get;set;}
    public String selectedFollowupTemplate{get;set;}
    public String selectedReminderTemplate{get;set;}
    
    
    public EventApi__Event__c event{get;set;}
    public Event_Templates__c eventTemplate{get;set;}
    Public List<SelectOption> opts;
    Public ApexPages.StandardController controller;
    Public Map<Id,EmailTemplate> allTemplates;
    public EventTemplateSetupCtrl(ApexPages.StandardController controller)
    {
        try{
            this.controller = controller;
            opts = new List<SelectOption>();
            allTemplates = new Map<Id,EmailTemplate>();
            for(EmailTemplate template : [select Id, Name, Subject, Body, HtmlValue ,FolderId,Markup 
                                          from EmailTemplate order by Name asc ])
                allTemplates.put(template.Id, template);
            opts.add(new SelectOption(' - Select - ', ' - Select - '));
            event = (EventApi__Event__c)controller.getRecord();
            eventTemplate = [Select ID,Name,Invitation_Template__c,Invitation_Template_ID__c,
                             Registration_Template__c,Registration_Template_ID__c,
                             Reminder_Template__c,Reminder_Template_ID__c,
                             Thank_you_Id__c,Thank_you_template_id__c,
                             Followup_Template__c,Followup_Template_ID__c
                             from Event_Templates__c where Event__c=:controller.getId() LIMIT 1];
            if(eventTemplate == null)
            {
                eventTemplate = new Event_Templates__c();
            }else{
                selectedInvitationTemplate = eventTemplate.Invitation_Template_ID__c;
                selectedFollowupTemplate = eventTemplate.Followup_Template_ID__c;
                selectedRegistrationTemplate = eventTemplate.Registration_Template_ID__c;
                selectedReminderTemplate = eventTemplate.Reminder_Template_ID__c;
                
            }
        }catch(Exception e){
            
        }
    }
    
    public List<SelectOption> getEmailTemplateOpts() {
        
        //if ( selectedEmailTemplateFolder != null ) 
        {
            
            Id selectedId = Label.Adobe_Event_FolderId; //(Id) selectedEmailTemplateFolder;
            for ( EmailTemplate et : allTemplates.values() ) {
                if( selectedId != null)
                {
                    if ( et.FolderId == selectedId )
                        opts.add(new SelectOption(et.Id, et.Name));
                }
                else{
                    opts.add(new SelectOption(et.Id, et.Name));
                }
            }
        }
        return opts;
    }
    
    public PageReference ClosePopup()
    {
        return new PageReference('/'+controller.getId());
    }
    
    public PageReference Save()
    {
        if(selectedInvitationTemplate != ' - Select - ' &&
           selectedFollowupTemplate != ' - Select - ' &&
           selectedRegistrationTemplate != ' - Select - ' &&
           selectedReminderTemplate != ' - Select - ')
        {
            eventTemplate.Event__c = controller.getId();
            eventTemplate.Invitation_Template_ID__c = selectedInvitationTemplate;
            eventTemplate.Invitation_Template__c = allTemplates.get(selectedInvitationTemplate).Name;
            eventTemplate.Followup_Template_ID__c = selectedFollowupTemplate;
            eventTemplate.Followup_Template__c = allTemplates.get(selectedFollowupTemplate).Name;
            eventTemplate.Registration_Template_ID__c = selectedRegistrationTemplate;
            eventTemplate.Registration_Template__c = allTemplates.get(selectedRegistrationTemplate).Name;
            eventTemplate.Reminder_Template_ID__c = selectedReminderTemplate;
            eventTemplate.Reminder_Template__c = allTemplates.get(selectedReminderTemplate).Name;
            upsert eventTemplate;
            return new PageReference('/'+controller.getId());
        }
        else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'All Fields are required.'));
            return null;
        }
    }
}